# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.random.random((3,3,3))

array([[[0.90897245, 0.52520541, 0.82943884],
        [0.45602399, 0.68483899, 0.09510314],
        [0.53699996, 0.63917197, 0.05991362]],

       [[0.37433129, 0.94987989, 0.71443793],
        [0.67052989, 0.72043636, 0.95147217],
        [0.04313441, 0.02545742, 0.90095641]],

       [[0.71754902, 0.11901892, 0.76966606],
        [0.24353976, 0.91201182, 0.41774979],
        [0.57945195, 0.42843895, 0.27987667]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern


In [4]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2] = z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
mat=np.random.random((5,5))
print("Before Normalization: \n",mat)
max,min=mat.max(),mat.min()
mat = (mat - min)/(max - min)
print("\nAfter Normalization: \n",mat)

Before Normalization: 
 [[0.005454   0.86631901 0.54283766 0.41184315 0.58634487]
 [0.18862563 0.40279054 0.71346251 0.81448007 0.87975334]
 [0.64831476 0.22192456 0.2932577  0.24170932 0.65341906]
 [0.81361902 0.21237896 0.73157461 0.74684776 0.72594806]
 [0.02613614 0.33372921 0.2948538  0.26954962 0.07772307]]

After Normalization: 
 [[0.         0.98463417 0.61464493 0.46481695 0.6644073 ]
 [0.20950677 0.45446281 0.80980104 0.9253422  1.        ]
 [0.7352868  0.24759319 0.3291821  0.27022246 0.74112496]
 [0.92435735 0.23667519 0.83051717 0.84798618 0.82408167]
 [0.02365567 0.37547233 0.33100769 0.30206545 0.08265941]]


# 5.  How to find common values between two arrays?

In [6]:
arr1=np.arange(1,11)
arr2=[ele for ele in range(0,11,2)]
arr2=np.array(arr2)
print(f"Array 1 : {arr1}\nArray 2 : {arr2}")
print(f"Common values: {np.intersect1d(arr1,arr2)}")

Array 1 : [ 1  2  3  4  5  6  7  8  9 10]
Array 2 : [ 0  2  4  6  8 10]
Common values: [ 2  4  6  8 10]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
today=np.datetime64('today','D')
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
tmrw=np.datetime64('today','D') + np.timedelta64(1,'D')
print(f"Yesterday : {yesterday}\nToday : {today}\nTomorrow : {tmrw}")

Yesterday : 2020-07-25
Today : 2020-07-26
Tomorrow : 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
ar1=np.arange(np.random.randint(1),np.random.randint(10))
ar2=np.arange(np.random.randint(1),np.random.randint(10))#,np.random.randint(1,3))
res=np.array_equal(ar1,ar2)
res

False

In [9]:
a=b=np.array([1,2,3])
res=np.array_equal(a,b)
res

True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [13]:
vector=np.random.random(10)
print(vector)
vector[vector.argmax()]=0
print(vector)

[0.30808901 0.29492447 0.16281074 0.99746292 0.16465783 0.64778414
 0.98224055 0.78456949 0.82981207 0.80765092]
[0.30808901 0.29492447 0.16281074 0.         0.16465783 0.64778414
 0.98224055 0.78456949 0.82981207 0.80765092]


# 9. How to print all the values of an array?

In [10]:
arr=np.array([2,4,5,3,0,7,8])
print(arr)
np.set_printoptions(threshold=np.inf)
print(arr)

[2 4 5 3 0 7 8]
[2 4 5 3 0 7 8]


# 10.Subtract the mean of each row of a matrix

In [19]:
row=np.random.rand(3,9)
print(row)
row=row-row.mean(axis=1, keepdims=True)
row

[[0.28681782 0.23856296 0.19879531 0.48727154 0.98961143 0.7419714
  0.6984331  0.76684037 0.18937938]
 [0.43308872 0.34972679 0.41919184 0.82703026 0.49723328 0.92412959
  0.40412969 0.57787134 0.11435273]
 [0.70844346 0.02824921 0.71069291 0.04093828 0.34459855 0.20593731
  0.87633088 0.35839689 0.82832316]]


array([[-0.22403588, -0.27229074, -0.31205839, -0.02358216,  0.47875773,
         0.2311177 ,  0.18757939,  0.25598667, -0.32147432],
       [-0.0721062 , -0.15546813, -0.08600307,  0.32183535, -0.00796164,
         0.41893467, -0.10106523,  0.07267642, -0.39084218],
       [ 0.25267561, -0.42751864,  0.25492506, -0.41482957, -0.1111693 ,
        -0.24983054,  0.42056303, -0.09737096,  0.37255531]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [45]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 3. 5. 1. 5. 5. 2. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [46]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([1.57433793, 1.11741068, 1.67218342, 1.0022606 , 1.26214671])

# 13.How to find the most frequent value in an array?

In [25]:
x=np.array([1,2,5,3,9,6,4,9,5,9,8,0,9,6])
np.bincount(x).argmax()

9

# 14.How to get the n largest values of an array


In [41]:
l=np.arange(10)
print(l[np.argsort(l)[-1:]])

[9]


# 15.How to create a record array from a regular array?

In [44]:
a1 = np.array(['A','B','c'])
a2 = np.array([1,2,3])
a3 = np.array(['Chocolate','Vanilla','Strawberry'])
rec = np.core.records.fromarrays([a2,a1,a3])
print(rec[0],rec[1],rec[2])

(1, 'A', 'Chocolate') (2, 'B', 'Vanilla') (3, 'c', 'Strawberry')
